# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
        POSTGRES_HOST: ${{ secrets.DB_CONFIG_HOST }}
        POSTGRES_PORT: 5432
        POSTGRES_USER: ${{ secrets.DB_CONFIG_USERNAME }}
        POSTGRES_PASSWORD: ${{ secrets.DB_CONFIG_PASSWORD }}
        TEST_DB: ${{ secrets.DB_CONFIG_TEST }}
    strategy:
      matrix:
        node-version: [ 14.x]
      

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
         node-version: ${{ matrix.node-version }}
         
         
      - name: Install dependencies
        run: yarn 
        

      
      - run: yarn test
  

  deploy-api-1:
    # Deploy the to the first VM
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy API to the Digital Ocean Droplet
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.DO_VM_1 }}
          username: root
          key: ${{ secrets.DO_API_KEY }}
          port: 22
          script: | 
            mkdir -p app 
            cd app 
            git clone https://github.com/NonsoAmadi10/BB_List.git . 
            chmod u+x prod.sh
            ./prod.sh
            echo 'Deployment successful'
  
  deploy-api-2:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy API to the Digital Ocean Droplet
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.DO_VM_2 }}
          username: root
          key: ${{ secrets.DO_API_KEY }}
          port: 22
          script: |
            mkdir -p app
            cd app
            git clone https://github.com/NonsoAmadi10/BB_List.git .
            chmod u+x prod.sh
            ./prod.sh
            echo 'Deployment successful'
      


